name: pet_hood
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter_svg: ^1.0.3
  like_button: ^2.0.4
  image_picker: ^0.8.5
  email_validator: ^2.0.1
  mask_text_input_formatter: ^2.3.0
  percent_indicator: ^4.0.0
  expansion_tile_card: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: Grand Hotel
      fonts:
        - asset: assets/fonts/GrandHotel-Regular.ttf
